server:
  port: 8080
#db:
#  spring:
#    datasource:
#      type: com.zaxxer.hikari.HikariDataSource
#      url: jdbc:mysql://localhost:3306/my
#      username: root
#      password: password
#    jpa:
#      hibernate.ddl-auto: update
#      generate-ddl: true
#      show-sql: true

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
#        format_sql: true
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
